version("1.0.0");
description("Chaosbox with Redis-backed counter");
selectors("worker");
resources {
  memory { min("64 mb"); max("512 mb"); };
  cpu { min("100 mhz"); max("1000 mhz"); };
  ports {
    chaosbox_http_port {
      protocol("http")
      exposure("public")
    };
  };
};
health_check {
  timeout_seconds(5);
  wait { attempts(30); interval_seconds(1); };
  readiness {
    http {
      port("chaosbox_http_port");
      path("/");
      expect_status(200);
      scheme("http");
    };
  };
};
